name: AOC Coccinelle CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up OCaml
      run: |
        sudo apt-get update
        sudo apt install ocaml

    - name: Clone Coccinelle source
      run: |
        git clone https://github.com/coccinelle/coccinelle.git
        cd coccinelle
        git checkout 1.3.0

    - name: Build Coccinelle
      run: |
        cd coccinelle
        ./autogen
        ./configure --prefix=/usr/local --disable-opt --with-python=python3
        sudo make
        sudo make install

    - name: Verify Coccinelle Installation
      run: |
        spatch --version

    - name: Install package and test dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Run tests
      run: |
        pytest
